version: '3.8'

networks:
  traefik_net:
    external: true
  backend_whisper:
    external: true

services:
  alerting_demo:
    container_name: alerting_demo
    build: .
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100k"
    ports:
      - 3000:3000
    environment:
      SEVERITY: warning
      CHANNEL: teams
      PORT: 3000
      LOG_LEVEL: info


